### ISSUE TITLE
ElecCore-1.11-1.7.407 Crash

### ISSUE THREAD

**Issue by blackstarxr253** [Elecs-Mods/ElecCore#101]
When using ElecCore-1.11-1.7.407 game crashes upon load/ However, when switched back to ElecCore-1.11-1.7.402 game loads without issue

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  FMLPlugin (InventoryTweaks-1.62-dev-77.jar)
  LoadingPlugin (ChunkAnimator-MC1.11-1.2.jar)
  BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
  LoadingPlugin (Quark-r1.2-83.jar)
Contact their authors BEFORE contacting forge

// There are four lights!

Time: 3/4/17 11:21 AM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at elec332.core.util.FMLUtil.loadClass(FMLUtil.java:22)
	at elec332.core.main.ElecCoreDiscoverer$AdvancedASMData.loadClass(ElecCoreDiscoverer.java:199)
	at elec332.core.main.APIHandler.processASMData(APIHandler.java:48)
	at elec332.core.main.ElecCoreDiscoverer.process(ElecCoreDiscoverer.java:146)
	at elec332.core.main.ElecCore.onConstructionLast(ElecCore.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:582)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalArgumentException: Unsupported MC version: 1.11.2
	at elec332.abstraction.manager.AbstractionManager.init(AbstractionManager.java:29)
	at elec332.abstraction.manager.AbstractionManager.<clinit>(AbstractionManager.java:47)
	... 39 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at elec332.core.util.FMLUtil.loadClass(FMLUtil.java:22)
	at elec332.core.main.ElecCoreDiscoverer$AdvancedASMData.loadClass(ElecCoreDiscoverer.java:199)
	at elec332.core.main.APIHandler.processASMData(APIHandler.java:48)
	at elec332.core.main.ElecCoreDiscoverer.process(ElecCoreDiscoverer.java:146)
	at elec332.core.main.ElecCore.onConstructionLast(ElecCore.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:246)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:224)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:582)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:440)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:352)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 539054864 bytes (514 MB) / 1453326336 bytes (1386 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.38 Powered by Forge 13.20.0.2252 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2252.jar) 
	UC	forge{13.20.0.2252} [Minecraft Forge] (forge-1.11.2-13.20.0.2252.jar) 
	UC	backpacks16840{3.1.7} [Backpacks!] (zz-backpacks 1.11.2 - 3.1.7.jar) 
	UC	actuallyadditions{1.11.2-r103} [Actually Additions] (ActuallyAdditions-1.11.2-r103.jar) 
	UC	akashictome{1.1-7} [Akashic Tome] (AkashicTome-1.1-7.jar) 
	UC	morphtool{1.1-13} [Morph-o-Tool] (Morph-o-Tool-1.1-13.jar) 
	UC	quark{r1.2-83} [Quark] (Quark-r1.2-83.jar) 
	UC	autoreglib{1.1-4} [AutoRegLib] (AutoRegLib-1.1-4.jar) 
	UC	baubles{1.4.3} [Baubles] (Baubles-1.11-1.4.3.jar) 
	UC	biomesoplenty{6.0.2.2161} [Biomes O' Plenty] (BiomesOPlenty-1.11.2-6.0.2.2161-universal.jar) 
	UC	guideapi{1.11-2.1.0-50} [Guide-API] (Guide-API-1.11-2.1.0-50.jar) 
	UC	bloodmagic{1.11-2.1.5-74} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.11-2.1.5-74.jar) 
	UC	chameleon{1.11-3.0.2} [Chameleon] (Chameleon-1.11-3.0.2.jar) 
	UC	chesttransporter{2.7.1} [Chest Transporter] (ChestTransporter-1.11.2-2.7.1.jar) 
	UC	chunkanimator{1.2} [Chunk Animator] (ChunkAnimator-MC1.11-1.2.jar) 
	UC	forestry{5.3.1.45} [Forestry] (forestry_1.11.2-5.3.1.45.jar) 
	UC	eleccore{1.7.407} [ElecCore] (ElecCore-1.11-1.7.407.jar) 
	UC	deepresonance{1.4.6} [DeepResonance] (deepresonance-1.1x-1.4.6.jar) 
	UC	elevatorid{1.3.0} [Elevator Mod] (ElevatorMod-1.11.2-1.3.0.jar) 
	UC	extrautils2{1.0} [extrautils2] (extrautils2-1.11.2-1.3.0.jar) 
	UC	zerocore{1.11.2-0.1.0.4} [Zero CORE] (zerocore-1.11.2-0.1.0.4.jar) 
	UC	bigreactors{1.11.2-0.4.5.27} [Extreme Reactors] (ExtremeReactors-1.11.2-0.4.5.27.jar) 
	UC	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UC	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UC	waila{1.8.10} [Waila] (Hwyla-1.8.10-B23_1.11.jar) 
	UC	inventorytweaks{1.62-dev-77-7812cce} [Inventory Tweaks] (InventoryTweaks-1.62-dev-77.jar) 
	UC	ironchest{1.11-7.0.17.799} [Iron Chest] (ironchest-1.11-7.0.17.799.jar) 
	UC	jei{4.2.7.241} [Just Enough Items] (jei_1.11.2-4.2.7.241.jar) 
	UC	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UC	jeresources{0.6.2.104} [Just Enough Resources] (JustEnoughResources-1.11.2-0.6.2.104.jar) 
	UC	llor{1.1.3-mc1.11.2} [Light Level Overlay Reloaded] (LLOverlayReloaded-1.1.3-mc1.11.2.jar) 
	UC	oreexcavation{1.3.85} [OreExcavation] (OreExcavation-1.3.85.jar) 
	UC	harvestcraft{1.11.2d} [Pam's HarvestCraft] (Pam's HarvestCraft 1.11.2d.jar) 
	UC	shetiphiancore{3.4.1} [ShetiPhian-Core] (shetiphiancore-1.11.0-3.4.2.jar) 
	UC	platforms{1.3.2} [Platforms] (platforms-1.11.0-1.3.2.jar) 
	UC	rangedpumps{0.4} [Ranged Pumps] (rangedpumps-0.4.jar) 
	UC	xreliquary{1.11.2-1.3.3.635} [Reliquary] (Reliquary-1.11.2-1.3.3.635.jar) 
	UC	rftools{5.85} [RFTools] (rftools-1.1x-5.85.jar) 
	UC	rftoolsdim{4.54} [RFTools Dimensions] (rftoolsdim-1.1x-4.54.jar) 
	UC	storagedrawers{1.11.2-4.2.0} [Storage Drawers] (StorageDrawers-1.11.2-4.2.0.jar) 
	U	denseores{1.0} [denseores] (denseores-1.11-alpha-1.0.0.jar) 
	Loaded coremods (and transformers): 
FMLPlugin (InventoryTweaks-1.62-dev-77.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (ChunkAnimator-MC1.11-1.2.jar)
  lumien.chunkanimator.asm.ClassTransformer
BCModPlugin (zz-backpacks 1.11.2 - 3.1.7.jar)
  brad16840.common.asm.ClassTransformer
ShetiPhian-ASM (shetiphiancore-1.11.0-3.4.2.jar)
  shetiphian.core.asm.ClassTransformer
LoadingPlugin (Quark-r1.2-83.jar)
  vazkii.quark.base.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13467 Compatibility Profile Context 21.19.413.0' Renderer: 'AMD Radeon (TM) R9 390 Series'
	Launched Version: forge-13.20.0.2252
	LWJGL: 2.9.4
	OpenGL: AMD Radeon (TM) R9 390 Series GL version 4.5.13467 Compatibility Profile Context 21.19.413.0, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8350 Eight-Core Processor 
```

**Comment by Elec332** [comment]
Fixed in latest release
