### ISSUE TITLE
Error: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Protheus** [Elecs-Mods/ElecCore#12]
MC: 1.8.9
Eleccore: ElecCore-1.8.9-1.4.220
Pastebin: http://pastebin.com/9hcfHMMt

See what you can find - no rush, just testing mods to work together in 1.8.9

WARNING: coremods are present:
  FldLoadingPlugin (FastLeafDecay-1.8-1.6.jar)
  LoadingPlugin (RandomThings-MC1.8.8-3.5.7.jar)
  FMLPlugin (InventoryTweaks-1.60-beta-30.jar)
Contact their authors BEFORE contacting forge

// Don't be sad. I'll do better next time, I promise!

Time: 1/23/16 9:23 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoSuchMethodError: elec332.core.util.BlockStateHelper.createMetaBlockState(Lnet/minecraft/block/Block;)Lnet/minecraft/block/state/BlockState;
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:162)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:739)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:307)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoSuchMethodError: elec332.core.util.BlockStateHelper.createMetaBlockState(Lnet/minecraft/block/Block;)Lnet/minecraft/block/state/BlockState;
    at elec332.craftingtableiv.blocks.BlockCraftingTableIV.func_180661_e(BlockCraftingTableIV.java:98)
    at net.minecraft.block.Block.<init>(Block.java:246)
    at net.minecraft.block.Block.<init>(Block.java:252)
    at elec332.core.tile.BlockTileBase.<init>(BlockTileBase.java:31)
    at elec332.craftingtableiv.blocks.BlockCraftingTableIV.<init>(BlockCraftingTableIV.java:33)
    at elec332.craftingtableiv.CraftingTableIV.init(CraftingTableIV.java:98)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:737)
    ... 10 more

**Comment by Elec332** [comment]
Fixed, this is actually a CraftingTable-IV bug, it should be on CF soon.
When you want to test new mods, you could also try E-Flux: http://minecraft.curseforge.com/projects/e-flux :3

**Comment by Protheus** [comment]
will have a look indeed - thank you for the prompt response :-)
