### ISSUE TITLE
Crash on loading/creating single player world

### ISSUE THREAD

**Issue by LemADEC** [Elecs-Mods/ElecCore#130]
As of ElecCore-1.12.2-1.8.434.jar, game crashes in single player when loading or creating world with spongeforge added to FTB Revelation 1.0.0.

```
java.lang.RuntimeException: java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\xxx\Documents\Curse\Minecraft\Instances\FTB Revelation\New World\extradata\eleccore.dat_new (Le chemin d’accès spécifié est introuvable)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:664)
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callWorldSaveEvent(SpongeForgeEventFactory.java:1282)
	at org.spongepowered.mod.event.SpongeForgeEventFactory.callForgeEvent(SpongeForgeEventFactory.java:538)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:302)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:357)
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:345)
	at net.minecraft.world.WorldServer.handler$onSaveAllChunks$zld000(WorldServer.java:2881)
	at net.minecraft.world.WorldServer.func_73044_a(WorldServer.java:1009)
	at org.spongepowered.common.world.WorldManager.saveWorld(WorldManager.java:531)
	at net.minecraft.server.MinecraftServer.func_71267_a(MinecraftServer.java:3951)
	at net.minecraft.server.integrated.IntegratedServer.func_71267_a(IntegratedServer.java:252)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:170)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\xxx\Documents\Curse\Minecraft\Instances\FTB Revelation\New World\extradata\eleccore.dat_new (Le chemin d’accès spécifié est introuvable)
	at elec332.core.util.IOUtil.writeWithBackup(IOUtil.java:73)
	at elec332.core.util.IOUtil$NBT.writeWithBackup(IOUtil.java:125)
	at elec332.core.server.SaveHandler.save(SaveHandler.java:83)
	at elec332.core.server.SaveHandler.access$100(SaveHandler.java:24)
	at elec332.core.server.SaveHandler$EventHandler.onWorldSave(SaveHandler.java:108)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_855_EventHandler_onWorldSave_Save.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:652)
	... 13 more
Caused by: java.io.FileNotFoundException: C:\Users\xxx\Documents\Curse\Minecraft\Instances\FTB Revelation\New World\extradata\eleccore.dat_new (Le chemin d’accès spécifié est introuvable)
	at java.io.FileOutputStream.open(Native Method)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at net.minecraft.nbt.CompressedStreamTools.func_74795_b(CompressedStreamTools.java:148)
	at elec332.core.util.IOUtil$NBT.write(IOUtil.java:137)
	at elec332.core.util.IOUtil$NBT$1.write(IOUtil.java:145)
	at elec332.core.util.IOUtil$NBT$1.write(IOUtil.java:141)
	at elec332.core.util.IOUtil.writeWithBackup(IOUtil.java:71)
	... 20 more
```

Steps to reproduce:
1- install FTB Revelation 1.0.0 with Curse launcher
2- launch, create new single player world, creative
3- close game, add Sponge, launch, reload same world => crash
4- restart game, create new world => crash
5- remove Sponge, restart game, load previous worlds => warning about sponge:human removal, loads ok

Adding sponge seems to interfere with elec332 ability to access files in the world folder.

https://gist.github.com/LemADEC/f214473f7ef58b94d3f5a8de9c750a96

See https://github.com/SpongePowered/SpongeForge/issues/1921

**Comment by Elec332** [comment]
Sponge again? Great...

**Comment by Elec332** [comment]
Fixed on Sponge's end
