### ISSUE TITLE
NPE on saving out the world on shutdown of server.

### ISSUE THREAD

**Issue by ProsperCraft** [Elecs-Mods/ElecCore#132]
https://gist.github.com/ProsperCraft/0caf60266456f2652b7a7a9ef5000cf1

forge-1.12.2-14.23.1.2598-universal.jar 
ElecCore-1.12.2-1.8.434.jar

**Comment by Elec332** [comment]
Do you have the entire server log?

**Comment by ProsperCraft** [comment]
[ProsperServerLogs.zip](https://github.com/Elecs-Mods/ElecCore/files/1648975/ProsperServerLogs.zip)

**Comment by ProsperCraft** [comment]
This is still happening.

Console- https://gist.github.com/ProsperCraft/b9757a617523a3f3b20be957e091e025

[2018-02-05-2.log.gz](https://github.com/Elecs-Mods/ElecCore/files/1696904/2018-02-05-2.log.gz)

**Comment by ayan4m1** [comment]
My environment:
```
CentOS 7 x64
Oracle JDK x64 1.8.0_181
Minecraft 1.12.2
FTB Revelation 2.3.0
```

The Revelation modpack is using `ElecCore-1.12.2-1.8.434.jar`

I have had the same problem. It is intermittent. When a player disconnects from a dedicated server instance, the server crashes with:

```
[02:00:01] [Server Shutdown Thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.PlayerEvent$PlayerLoggedOutEvent@2586c5ba:
java.lang.NullPointerException: null
        at elec332.core.server.ServerHelper$EventHandler.onPlayerDisconnected(ServerHelper.java:420) ~[ServerHelper$EventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_992_EventHandler_onPlayerDisconnected_PlayerLoggedOutEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:579) [FMLCommonHandler.class:?]
        at net.minecraft.server.management.PlayerList.func_72367_e(PlayerList.java:387) [pl.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:849) [pa.class:?]
        at net.minecraft.network.NetworkManager.func_179293_l(NetworkManager.java:453) [gw.class:?]
        at net.minecraft.network.NetHandlerPlayServer$2.run(NetHandlerPlayServer.java:291) [pa$2.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
        at net.minecraft.server.MinecraftServer.func_175586_a(MinecraftServer.java:1383) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_152344_a(MinecraftServer.java:1395) [MinecraftServer.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_194028_b(NetHandlerPlayServer.java:287) [pa.class:?]
        at net.minecraft.server.management.PlayerList.func_72392_r(PlayerList.java:1083) [pl.class:?]
        at net.minecraft.server.MinecraftServer.func_71260_j(MinecraftServer.java:431) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$4.run(MinecraftServer.java:1579) [MinecraftServer$4.class:?]
```

EDIT: In my case, this was a side-effect from auto-restarting the server.

Here is the full debug.log for you - [debug-1.log](https://github.com/Elecs-Mods/ElecCore/files/2315012/debug-1.log)
