### ISSUE TITLE
Crash on World Load

### ISSUE THREAD

**Issue by themooer1** [Elecs-Mods/ElecCore#141]
Running FTB Revelations 2.6.0

The forge server finishes postinitialization, then, once the minecraft server finishes loading the world, the NBTUnserializer used by SaveHandler.java:load(World world) throws a nullPointerException.

Here is the partial stacktrace ([Crash Report](https://pastebin.com/Qi4QdTg4)):

```
java.lang.RuntimeException: java.lang.NullPointerException
        at elec332.core.nbt.NBTMap.deserializeNBT(NBTMap.java:163) ~[NBTMap.class:?]
        at elec332.core.server.ServerHelper.load(ServerHelper.java:320) ~[ServerHelper.class:?]
        at elec332.core.server.SaveHandler.load(SaveHandler.java:60) ~[SaveHandler.class:?]
        at elec332.core.server.SaveHandler.access$000(SaveHandler.java:24) ~[SaveHandler.class:?]
        at elec332.core.server.SaveHandler$EventHandler.onWorldLoad(SaveHandler.java:101) ~[SaveHandler$EventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1091_EventHandler_onWorldLoad_Load.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
        at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:309) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at elec332.core.server.ElecPlayer.deserializeNBT(ElecPlayer.java:57) ~[ElecPlayer.class:?]
        at elec332.core.server.ElecPlayer.deserializeNBT(ElecPlayer.java:16) ~[ElecPlayer.class:?]
        at elec332.core.nbt.NBTMap.deserializeNBT(NBTMap.java:153) ~[NBTMap.class:?]
        ... 11 more
```

Thanks

**Comment by Elec332** [comment]
Fixed
https://minecraft.curseforge.com/projects/eleccore/files/2678966
