### ISSUE TITLE
Crash (1.7.10)

### ISSUE THREAD

**Issue by Cronosus** [Elecs-Mods/ElecCore#39]
Crash on loading server
http://pastebin.com/HgN2qr3h

**Comment by jusitnboggs** [comment]
I get the same error more or less

`Time: 5/23/16 3:14 AM
Description: Exception in server tick loop

java.lang.RuntimeException: java.io.IOException: Root tag must be a named compound tag
    at elec332.core.server.ServerHelper.fromFile(ServerHelper.java:308)
    at elec332.core.server.ServerHelper$EventHandler.onWorldLoad(ServerHelper.java:204)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler_83_EventHandler_onWorldLoad_Load.invoke(.dynamic)
    at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
    at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:230)
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:258)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
Caused by: java.io.IOException: Root tag must be a named compound tag
    at net.minecraft.nbt.CompressedStreamTools.func_152456_a(CompressedStreamTools.java:133)
    at net.minecraft.nbt.CompressedStreamTools.func_152458_a(CompressedStreamTools.java:216)
    at net.minecraft.nbt.CompressedStreamTools.func_74797_a(CompressedStreamTools.java:200)
    at elec332.core.server.ServerHelper.fromFile(ServerHelper.java:291)
    ... 8 more`

**Comment by jusitnboggs** [comment]
Did this bug get fixed?

**Comment by Cronosus** [comment]
yours, no
i have today this same
