### ISSUE TITLE
Server Crash java.lang.NullPointerException: Exception in server tick loop 	at elec332.core.grid.v2.AbstractGridHandler$1.onChange(AbstractGridHandler.java:34)

### ISSUE THREAD

**Issue by ProsperCraft** [Elecs-Mods/ElecCore#59]
http://pastebin.com/jk306eit

Modpack - Allthemods 1.35 - with embers mod disabled

java.lang.NullPointerException: Exception in server tick loop
    at elec332.core.grid.v2.AbstractGridHandler$1.onChange(AbstractGridHandler.java:34)
    at elec332.core.grid.v2.AbstractGridHandler$1.onChange(AbstractGridHandler.java:31)
    at elec332.core.world.PositionedObjectHolder$PositionChunk.remove(PositionedObjectHolder.java:132)
    at elec332.core.world.PositionedObjectHolder$PositionChunk.access$300(PositionedObjectHolder.java:103)
    at elec332.core.world.PositionedObjectHolder.remove(PositionedObjectHolder.java:75)
    at elec332.core.grid.v2.AbstractGridHandler.removeObject(AbstractGridHandler.java:190)
    at elec332.core.grid.v2.AbstractGridHandler.unloadObjects_Internal(AbstractGridHandler.java:150)
    at elec332.core.grid.v2.AbstractGridHandler.checkChunkUnload(AbstractGridHandler.java:137)
    at elec332.core.grid.v2.internal.GridEventInputHandler.tickEnd(GridEventInputHandler.java:101)
    at elec332.core.grid.v2.internal.GridEventHandler.serverTick(GridEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_353_GridEventHandler_serverTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Elec332** [comment]
Please post the entire log and modlist

**Comment by ProsperCraft** [comment]
Please click on the pastebin link which includes all of that information.

**Comment by maxhenkes** [comment]
Got the same crash just now:
Forge 2094, Eleccore 1.6.326:

http://pastebin.com/xGuHnnpC

User was attempting to craft Deep Resonance tanks when the crash happened. DR is also the only mod that requires this library.

Modlist can be found here (bottom):
https://minecraft.curseforge.com/projects/tranquility/files/2336392

EDIT:
He crafted those a minute before the crash, sorry might be completely unrelated
