### ISSUE TITLE
Crash when the server finished starting

### ISSUE THREAD

**Issue by quantumsheep** [Elecs-Mods/ElecCore#61]
The crash error:

`[11:21:48] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.UnsupportedOperationException
    at com.google.common.collect.ImmutableCollection.clear(ImmutableCollection.java:156) ~[minecraft_server.1.10.2.jar:?]
    at elec332.core.grid.v2.internal.GridEventInputHandler.tickEnd(GridEventInputHandler.java:113) ~[GridEventInputHandler.class:?]
    at elec332.core.grid.v2.internal.GridEventHandler.serverTick(GridEventHandler.java:49) ~[GridEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_305_GridEventHandler_serverTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261) ~[FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

Full crash report: http://pastebin.com/Qpq7SgpT

**Comment by Elec332** [comment]
Fixed in upcoming release

**Comment by dpeter99** [comment]
When will the next release uploaded?

**Comment by kythorn** [comment]
He uploaded it almost immediately, Curse is just being slow for some reason. If you need it fast, go here:

https://minecraft.curseforge.com/projects/eleccore-rendering-library/files

**Comment by dpeter99** [comment]
THX 😄

**Comment by quantumsheep** [comment]
Thanks! Fast answer!
