### ISSUE TITLE
server crash java.lang.IllegalStateException     at elec332.core.grid.AbstractGridHandler.checkChunkLoad(AbstractGridHandler.java:176)

### ISSUE THREAD

**Issue by Dongonzales** [Elecs-Mods/ElecCore#75]
java.lang.IllegalStateException
    at elec332.core.grid.AbstractGridHandler.checkChunkLoad(AbstractGridHandler.java:176) ~[AbstractGridHandler.class:?]
    at elec332.core.grid.internal.GridEventInputHandler.tickEnd(GridEventInputHandler.java:108) ~[GridEventInputHandler.class:?]
    at elec332.core.grid.internal.GridEventHandler.serverTick(GridEventHandler.java:49) ~[GridEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_231_GridEventHandler_serverTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:137) ~[EventBus.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:93) ~[EventBus.class:?]
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261) ~[FMLCommonHandler.class:?]
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) ~[MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_112]

**Comment by john01dav** [comment]
My public server is experiencing this same bug. I am running Sponge version 1.10.2-2171-5.1.0-BETA-1983, and removing Sponge, starting server, stopping server, then re-adding Sponge seems to temporarily fix the issue, but, it then quickly returns a few hours later. A restart with Sponge installed simply causes the crash to occur again shortly after launch (anywhere from the instant startup finishes to a few minutes after launch once a few players are online). I am using the Direwolf20 1.10 pack in the latest release version with ElecCore 1.10.2-1.6.345 and Forge 1.10.2-12.18.2.2171-universal. 

Stack Trace:
```
java.lang.IllegalStateException
        at elec332.core.grid.AbstractGridHandler.checkChunkLoad(AbstractGridHandler.java:176)
        at elec332.core.grid.internal.GridEventInputHandler.tickEnd(GridEventInputHandler.java:108)
        at elec332.core.grid.internal.GridEventHandler.serverTick(GridEventHandler.java:49)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_302_GridEventHandler_serverTick_ServerTickEvent.invoke(.dynamic)
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:137)
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:93)
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
        at java.lang.Thread.run(Thread.java:745)
[crash-2016-12-20_01.14.13-server.txt](https://github.com/Elecs-Mods/ElecCore/files/662490/crash-2016-12-20_01.14.13-server.txt)



```

I am beginning to lose players because this bug prevents me from keeping my server online. I would appreciate a quick fix -- this is very urgent to me.

I have also included the crash report and server logs.
[logs.zip](https://github.com/Elecs-Mods/ElecCore/files/662498/logs.zip)

**Comment by john01dav** [comment]
I am also now receiving the attached crash report in addition to the previous one, albeit, slightly less commonly. 
[crash-2016-12-20_06.18.20-server.txt](https://github.com/Elecs-Mods/ElecCore/files/662827/crash-2016-12-20_06.18.20-server.txt)
[fml-server-3.log.txt](https://github.com/Elecs-Mods/ElecCore/files/662830/fml-server-3.log.txt)

I am nearing the point where I need to start removing mods from the pack and thus causing irreversible world damage. I can't be babysitting my server 24/7 to add/remove spogne.

**Comment by Aaron1011** [comment]
@john01dav @Dongonzales: Try using [this build](https://www.dropbox.com/s/m5jvo1o6n5wph0t/ElecCore-1.10.2-1.6.localBuild-fake-1.6.345.jar?dl=0) (Source at https://github.com/Aaron1011/ElecCore/commit/9b04dae02808b7740d8fa4fd53eb7063d7cb6b28). I've added some extra information to the exception being printed out, which should help to debug this.

I'm almost certain that this is a Sponge issue, as I've talked t several other people who've been experiencing it. We should continue the discussion here: https://github.com/SpongePowered/SpongeForge/issues/992

**Comment by john01dav** [comment]
@Aaron1011 The issue came back with the following stack trace:
```[00:05:37] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@25ab81a2:
java.lang.IllegalStateException: Some chunkcheck failed! Instance: mcjty.deepresonance.tanks.TankGridHandler@190c8a32 mcjty.deepresonance.tanks.TankGridHandler Position: [DimensionCoordinate: BlockPos{x=958, y=56, z=-1037} dim: 0] Object:
 mcjty.deepresonance.tanks.TankTileLink@6c267a4b TileEntity: mcjty.deepresonance.blocks.tank.TileTank@3d0c8050 oldUpdates: [[DimensionCoordinate: BlockPos{x=958, y=56, z=-1037} dim: 0]] add: [] changeCheck: [] updates: [[DimensionCoordina
te: BlockPos{x=958, y=56, z=-1037} dim: 0]] dimCoord: [DimensionCoordinate: BlockPos{x=958, y=56, z=-1037} dim: 0]
        at elec332.core.grid.AbstractGridHandler.checkChunkLoad(AbstractGridHandler.java:176) ~[AbstractGridHandler.class:?]
        at elec332.core.grid.internal.GridEventInputHandler.tickEnd(GridEventInputHandler.java:108) ~[GridEventInputHandler.class:?]
        at elec332.core.grid.internal.GridEventHandler.serverTick(GridEventHandler.java:49) ~[GridEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_302_GridEventHandler_serverTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:137) [EventBus.class:?]
        at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:93) [EventBus.class:?]
        at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]```

**Comment by RaresKool** [comment]
Having the same issue. Running ElecCore-1.10.2-1.6.345 and also using Sponge.
```
Description: Exception in server tick loop
 
java.lang.IllegalStateException
    at elec332.core.grid.AbstractGridHandler.checkChunkLoad(AbstractGridHandler.java:176)
    at elec332.core.grid.internal.GridEventInputHandler.tickEnd(GridEventInputHandler.java:108)
    at elec332.core.grid.internal.GridEventHandler.serverTick(GridEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_300_GridEventHandler_serverTick_ServerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:137)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:93)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)
```

**Comment by Sir-Will** [comment]
Same issue here, deleting the player file of the joining player fixes it. What do I have to delete inside the player file to fix this crash? I don't want to wipe the player file every time.

**Comment by Elec332** [comment]
The version with a workaround for this will be released today or tomorrow

**Comment by Sir-Will** [comment]
Unfortunately I will have to wait for a modpack then too. So it would be great to know what exactly I have to remove in the player file.

**Comment by Eufranio** [comment]
Are you sure It's fixed? Because I crashed with this exact crash today:
```
java.lang.IllegalStateException
	at elec332.core.grid.AbstractGridHandler.checkChunkLoad(AbstractGridHandler.java:177)
	at elec332.core.grid.internal.GridEventInputHandler.tickEnd(GridEventInputHandler.java:108)
	at elec332.core.grid.internal.GridEventHandler.serverTick(GridEventHandler.java:49)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_210_GridEventHandler_serverTick_ServerTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:637)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:593)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:261)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:657)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)
```
Full crash-report: https://hastebin.com/kularuxifu.sql

**Comment by Eufranio** [comment]
Or the fix wasn't backported to 1.10, I guess?

**Comment by Aaron1011** [comment]
@Eufranio: Would you be able to join `#spongedev` on `irc.esper.net` to discuss this further?

**Comment by Eufranio** [comment]
I prefer Discord, but ok.

**Comment by Aaron1011** [comment]
This issue [has been fixed in SpongeForge](https://github.com/SpongePowered/SpongeForge/issues/992#issuecomment-275866967) - it was a bug in how Sponge handled chunkloading..
