### ISSUE TITLE
[Mod Incompatibility] Client Tweaks (invalid)

### ISSUE THREAD

**Issue by sscards55** [Elecs-Mods/ElecCore#96]
I just updated from ElecCore 1.6.379 to 1.7.407 and this happened. This is the only mod I changed.

	java.lang.NullPointerException: Unexpected error
	at net.blay09.mods.clienttweaks.tweak.AutoJumpMoreLikeAutoDumbAmirite.onClientTick(AutoJumpMoreLikeAutoDumbAmirite.java:20)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_665_AutoJumpMoreLikeAutoDumbAmirite_onClientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1851)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

That says client tweaks but,

	UCE	eleccore{1.7.407} [ElecCore] (ElecCore-1.10.2-1.7.407.jar) 
	UCE	deepresonance{1.4.5} [DeepResonance] (deepresonance-1.1x-1.4.5.jar)

**Comment by Elec332** [comment]
This doen't tell me anything, you have to upload the full log in order for me to determine if ElecCore has anything to do with it

**Comment by sscards55** [comment]
It didn't happen the first time for some reason, but after I tried to crash the game again, there was a dependency error for forge. Only for a split second.
I was using 2221 instead of 2239.
Sorry for bothering you.

**Comment by Elec332** [comment]
No problem
